version: '3.9'
services:
  oncall-mysql:
    hostname: oncall-mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - iris

  oncall-web:
    build:
      context: .
    hostname: oncall
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - DOCKER_DB_BOOTSTRAP=1
      - IRIS_API_HOST=iris
    volumes:
      - ./configs/config.docker.yaml:/home/oncall/config/config.yaml
    networks:
      - iris
    depends_on:
      - oncall-mysql

#  oncall-metrics:
#    build:
#      context: ./metrics/
#    ports:
#      - "8090:8090"
#    environment:
#      - HOST=oncall-web
#      - PORT=8090
#    networks:
#      - iris

  custom-exporter:
    build:
     context: ./custom_exporter/
    ports:
     - "8082:8082"
    networks:
     - iris
    depends_on:
      - oncall-web

  oncall-prometheus:
    image: prom/prometheus:v2.36.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iris

  blackbox:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    restart: unless-stopped
    command:
      - "--config.file=/etc/blackbox/blackbox.yml"
    volumes:
      - ./blackbox.yml:/etc/blackbox/blackbox.yml
    networks:
      - iris

  grafana:
    build: './grafana'
    container_name: 'grafana'
    ports:
      - '3000:3000'
    networks:
      - iris

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.9.1"
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
    ports:
        - "9200:9200"
    volumes:
        - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - iris

  kibana:
    image: "docker.elastic.co/kibana/kibana:7.9.1"
    ports:
        - "5601:5601"
    networks:
      - iris

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.9.1"
    user: root
    volumes:
        - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
        - /var/lib/docker:/var/lib/docker
        - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - iris

  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude'
      - '^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)'
    networks:
      - iris


# **********************************************

volumes:
  elasticsearch_data:
  grafana-data:
  grafana-configs:


networks:
  iris:
    name: iris
