{
 "title": "Oncall-web",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "process_cpu_seconds_total " }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "process_virtual_memory_bytes" },
    { "expr": "process_resident_memory_bytes " }
   ]
  },
  {
   "title": "Notifier Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "oncallnotifier_message_sent_cnt "
    },
    {
     "expr": "oncallnotifier_message_fail_cnt"
    },
    {
     "expr": "oncallnotifier_message_blackhole_cnt "
    }
   ]
  }
 ]
}